# Generated by Django 4.0.3 on 2023-03-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255, verbose_name='First Name')),
                ('LastName', models.CharField(max_length=255, verbose_name='Last Name')),
                ('MiddleName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Name')),
                ('PhoneNumber', models.CharField(max_length=255, verbose_name='Phone Number')),
                ('GhanaCard', models.CharField(max_length=255, verbose_name='Ghana Card Number')),
            ],
        ),
    ]
