# Generated by Django 4.0.3 on 2023-03-30 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='dateSignedUp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='dateofbirth',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Birth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default=-1989, max_length=255, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
