# Generated by Django 4.0.3 on 2023-05-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_datesignedup_client_dateofbirth_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='MiddleName',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
    ]
