# Generated by Django 4.0.3 on 2023-03-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='blog_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cover_picture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
    ]
