# Generated by Django 4.0.3 on 2023-03-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareTakerChief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoolName', models.CharField(max_length=255, verbose_name='Stool Name')),
                ('Title', models.CharField(max_length=255, verbose_name='Title')),
                ('PhoneNumber', models.CharField(max_length=255, verbose_name='Phone Number')),
                ('Address', models.CharField(max_length=255, verbose_name='Address')),
            ],
        ),
    ]
