# Generated by Django 4.0.3 on 2023-04-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caretakerchief',
            old_name='Title',
            new_name='FullName',
        ),
    ]
