# Generated by Django 4.0.3 on 2023-04-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0002_rename_title_caretakerchief_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretakerchief',
            name='id',
        ),
        migrations.AddField(
            model_name='caretakerchief',
            name='chiefid',
            field=models.CharField(auto_created=True, default=1, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
