# Generated by Django 4.0.3 on 2023-04-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0003_remove_caretakerchief_id_caretakerchief_chiefid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretakerchief',
            name='chiefid',
        ),
        migrations.AddField(
            model_name='caretakerchief',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
