# Generated by Django 4.0.3 on 2023-06-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0004_remove_caretakerchief_chiefid_caretakerchief_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretakerchief',
            name='FullName',
            field=models.CharField(max_length=255, verbose_name='full Name'),
        ),
    ]
