# Generated by Django 4.0.3 on 2023-06-22 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0006_caretakerchief_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caretakerchief',
            old_name='User',
            new_name='user',
        ),
    ]
