# Generated by Django 4.0.3 on 2023-06-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0007_rename_user_caretakerchief_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caretakerchief',
            old_name='user',
            new_name='ctchief',
        ),
    ]
