# Generated by Django 4.0.3 on 2023-04-30 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='CareTakerChief',
        ),
    ]
