# Generated by Django 4.0.3 on 2023-04-30 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0004_remove_caretakerchief_chiefid_caretakerchief_id'),
        ('allocation', '0002_remove_allocation_caretakerchief'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='CareTakerChief',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chief.caretakerchief'),
            preserve_default=False,
        ),
    ]
