# Generated by Django 4.0.3 on 2023-05-11 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_middlename'),
        ('chief', '0004_remove_caretakerchief_chiefid_caretakerchief_id'),
        ('lands', '0001_initial'),
        ('allocation', '0003_allocation_caretakerchief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='CareTakerChief',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chief.caretakerchief'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='land',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocated', to='lands.land'),
        ),
    ]
