# Generated by Django 4.0.3 on 2023-05-11 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_middlename'),
        ('allocation', '0004_alter_allocation_caretakerchief_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
