# Generated by Django 4.0.3 on 2023-05-11 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0004_remove_caretakerchief_chiefid_caretakerchief_id'),
        ('allocation', '0005_alter_allocation_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='CareTakerChief',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chief.caretakerchief'),
        ),
    ]
