# Generated by Django 4.0.3 on 2023-06-21 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0006_caretakerchief_user'),
        ('allocation', '0008_alter_allocation_caretakerchief'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationChit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofallocation', models.DateField(auto_now=True)),
                ('clientfullname', models.CharField(max_length=255)),
                ('land', models.CharField(max_length=255)),
                ('CareTakerChief', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocatedcaretakerchief', to='chief.caretakerchief')),
            ],
        ),
    ]
